spring.application.name=the-trinity-dashboard
spring.datasource.url=jdbc:mysql://localhost:3306/trinity_db
spring.datasource.username=brandon
spring.datasource.password=nupzox7123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081